### PR TITLE
Add forgoten translation

### PR DESCRIPTION
**Pull request by miguel456**
PR adds forgotten line at top of the file.

### CODE REVIEW

**Comment by DaPigGuy** [comment]
Also, remove #Needs translation on line 100. Thanks.

**Comment by DaPigGuy** [comment]
Thank you!

**Comment by miguel456** [comment]
Sorry for forgetting so many things...
You're welcome!

**Comment by ghost** [comment]
https://www.mediafire.com/download/gsynfu387r7q1lt

**Comment by DaPigGuy** [comment]
@lolmanz0 You forgot the new-player translation.

**Pull request merged**
