### PR TITLE
Create lang_tur.yml

### PR DESCRIPTION
**Pull request by SuperAdam47**
# DO NOT REMOVE THIS
Please make sure your pull request complies with these guidelines:
- * [x] Use same formatting
- * [x] Must test on PMMP
- * [x] ***PLEASE*** don't use the GitHub Web Editor
- * [x] Have a detailed title like "Fix players are being kicked randomly"

If you are translating, make sure you translation complies with these guidelines:
- * [x] File must be named lang_iso. ISO Codes for languages can be found [here.](https://www.loc.gov/standards/iso639-2/php/code_list.php)
- * [x] ***PLEASE*** don't use Google Translate (or any other translators...)
- * [x] Translate messages but keep tags like {player} or {pin} the same
- * [x] Make a Pull Request named Translation for Language after you're finished

### CODE REVIEW

**Review by SalmonDE — CHANGES_REQUESTED** [review]
From my perspective this looks overall good. I can't be sure of the quality of the translation, but I'm trusting @SuperAdam47 in this case.

However at the first line of lang_tur.yml you should put in
#By @SuperAdam47 

https://github.com/DaPigGuy/PiggyAuth/pull/101/files#diff-01f1e499ac0c83feef1f61fa5f29697aR1

**Comment by SuperAdam47** [comment]
I wrote it all in quality

**Comment by SalmonDE** [comment]
Yes I said I trust the quality of your translation

**Review by SalmonDE — APPROVED** [review]

**Comment by SalmonDE** [comment]
#100 for reference

**Pull request merged**
