### PR TITLE
1.0.6 Update.

### PR DESCRIPTION
**Pull request by ghost**
I hate this update.

### CODE REVIEW

**Comment by ghost** [comment]
Fatal error: Class PiggyAuth\Packet\BossEventPacket contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (pocketmine\network\mcpe\protocol\DataPacket::handle) in phar:///root/hub/plugins/phar_PiggyAuth-patch-1_W3iEctXq6IIk6pX.phar/src/PiggyAuth/Packet/BossEventPacket.php on line 23


Yes, i hate this update. Good luck @MCPEPIG

**Comment by MCPEPIG** [comment]
Do you even know what you're doing? The plugin had used PiggyAuth\Packet\BossEventPacket and you deleted it... You would have to change it to pocketmine\network\mcpe\BossEventPacket or just not delete it from the plugin...

**Comment by DaPigGuy** [comment]
These changes aren't in the master branch for PocketMine yet...

**Comment by ghost** [comment]
YET.

**Pull request closed without merging**
